use movies;
--1
SELECT TITLE, NAME
FROM MOVIEEXEC ME JOIN MOVIE M ON PRODUCERC# = CERT#
WHERE NAME IN
(SELECT NAME
FROM MOVIEEXEC ME JOIN MOVIE M ON PRODUCERC# = CERT#
WHERE TITLE = 'Star Wars')

--2
SELECT DISTINCT NAME
FROM (MOVIEEXEC ME JOIN MOVIE M ON CERT# = PRODUCERC#)
JOIN STARSIN S ON TITLE = MOVIETITLE AND YEAR = MOVIEYEAR
WHERE STARNAME = 'Harrison Ford'

--3
SELECT DISTINCT NAME, STARNAME
FROM (STUDIO ST JOIN MOVIE M ON NAME = STUDIONAME)
JOIN STARSIN S ON TITLE = MOVIETITLE AND YEAR = MOVIEYEAR
ORDER BY NAME

--4
SELECT STARNAME, NETWORTH, TITLE
FROM (MOVIEEXEC ME JOIN MOVIE M ON CERT# = PRODUCERC#)
JOIN STARSIN S ON TITLE = MOVIETITLE AND YEAR = MOVIEYEAR
WHERE NETWORTH >= ALL (SELECT NETWORTH FROM MOVIEEXEC)

--5
SELECT NAME, MOVIETITLE
FROM MOVIESTAR MS LEFT JOIN STARSIN S ON NAME = STARNAME
WHERE MOVIETITLE IS NULL


use pc;
--1
SELECT MAKER, P.MODEL, TYPE
FROM PRODUCT P LEFT JOIN LAPTOP L ON P.MODEL = L.MODEL
WHERE P.TYPE = 'Laptop' AND L.CODE IS NULL
UNION
SELECT MAKER, P.MODEL, TYPE
FROM PRODUCT P LEFT JOIN PC ON P.MODEL = PC.MODEL
WHERE P.TYPE = 'PC' AND PC.CODE IS NULL
UNION
SELECT MAKER, P.MODEL, P.TYPE
FROM PRODUCT P LEFT JOIN PRINTER PR ON P.MODEL = PR.MODEL
WHERE P.TYPE = 'Printer' AND PR.CODE IS NULL

--2
SELECT DISTINCT P1.MAKER
FROM PRODUCT P1 JOIN PRODUCT P2 ON P1.MAKER = P2.MAKER
WHERE P1.TYPE = 'Laptop' AND P2.TYPE = 'Printer'

--3
SELECT DISTINCT L1.HD
FROM LAPTOP L1 JOIN LAPTOP L2 ON L1.HD = L2.HD AND L1.CODE != L2.CODE

--4
SELECT *
FROM PC JOIN PRODUCT P ON PC.MODEL = P.MODEL
WHERE MAKER IS NULL


use ships;
--1
SELECT *
FROM SHIPS S JOIN CLASSES C ON S.CLASS = C.CLASS

--2
SELECT *
FROM SHIPS S RIGHT JOIN CLASSES C ON S.CLASS = C.CLASS
WHERE NAME IS NOT NULL OR C.CLASS IN (SELECT NAME FROM SHIPS)

--3
SELECT COUNTRY, NAME
FROM (CLASSES C JOIN SHIPS S ON C.CLASS = S.CLASS)
LEFT JOIN OUTCOMES O ON NAME = SHIP
WHERE O.BATTLE IS NULL
ORDER BY COUNTRY

--4
SELECT NAME AS SHIPNAME
FROM CLASSES C JOIN SHIPS S ON C.CLASS = S.CLASS
WHERE NUMGUNS >= 7 AND LAUNCHED = 1916

--5
SELECT S.NAME, B.NAME, DATE
FROM (SHIPS S JOIN OUTCOMES O ON S.NAME = O.SHIP)
JOIN BATTLES B ON O.BATTLE = B.NAME
WHERE RESULT = 'sunk'
ORDER BY B.NAME

--6
SELECT NAME, DISPLACEMENT, LAUNCHED
FROM CLASSES C JOIN SHIPS S ON C.CLASS = S.CLASS
WHERE NAME = C.CLASS

--7
SELECT *
FROM CLASSES
WHERE CLASS NOT IN (SELECT DISTINCT CLASS FROM SHIPS)

--8
SELECT S.NAME, DISPLACEMENT, NUMGUNS, RESULT
FROM (SHIPS S JOIN OUTCOMES O ON S.NAME = O.SHIP)
JOIN CLASSES C ON C.CLASS = S.CLASS
WHERE O.BATTLE = 'North Atlantic'
