use movies;
--1
SELECT TITLE, YEAR, LENGTH
FROM MOVIE
WHERE YEAR < 2000 AND (LENGTH IS NULL OR LENGTH > 120)

--2
SELECT NAME, GENDER, BIRTHDATE
FROM MOVIESTAR
WHERE NAME LIKE 'J%' AND BIRTHDATE > '1948-12-31'

--3
SELECT S.NAME, COUNT(DISTINCT STARNAME) NUM_ACTORS
FROM MOVIE M JOIN STUDIO S ON M.STUDIONAME = S.NAME
JOIN STARSIN SI ON M.TITLE = SI.MOVIETITLE AND M.YEAR = SI.MOVIEYEAR
GROUP BY S.NAME

--4
SELECT MS.NAME, COUNT(STARNAME) NUM_MOVIES
FROM MOVIESTAR MS LEFT JOIN STARSIN SI
ON MS.NAME = SI.STARNAME
GROUP BY MS.NAME

--5
SELECT STUDIONAME, TITLE, YEAR
FROM MOVIE M
WHERE YEAR >= ALL
(SELECT YEAR FROM MOVIE WHERE STUDIONAME = M.STUDIONAME)

--6
SELECT NAME
FROM MOVIESTAR MS
WHERE GENDER = 'M'
AND
MS.BIRTHDATE >= ALL (SELECT BIRTHDATE FROM MOVIESTAR WHERE GENDER = 'M')

--7
SELECT STUDIONAME, STARNAME, COUNT(*) AS NUM_MOVIES
FROM MOVIE M JOIN STARSIN S ON
M.TITLE = S.MOVIETITLE AND M.YEAR = S.MOVIEYEAR
GROUP BY STUDIONAME, STARNAME
HAVING COUNT(*) =
(SELECT TOP 1 COUNT(*) AS NUM_MOVIES
FROM MOVIE JOIN STARSIN ON
TITLE = MOVIETITLE AND YEAR = MOVIEYEAR
GROUP BY STUDIONAME, STARNAME
HAVING STUDIONAME = M.STUDIONAME
ORDER BY NUM_MOVIES DESC)

--8
SELECT TITLE, YEAR, COUNT(STARNAME) AS NUM_ACTORS
FROM MOVIE M JOIN STARSIN S
ON
M.TITLE = S.MOVIETITLE AND M.YEAR = S.MOVIEYEAR
GROUP BY YEAR, TITLE
HAVING COUNT(STARNAME) > 2


use ships;
--1
SELECT DISTINCT NAME
FROM SHIPS
WHERE (NAME LIKE 'C%' OR NAME LIKE 'K%')
AND NAME IN (SELECT SHIP FROM OUTCOMES)

--2
SELECT DISTINCT S.NAME, C.COUNTRY
FROM CLASSES C JOIN SHIPS S ON C.CLASS = S.CLASS
LEFT JOIN OUTCOMES O ON S.NAME = O.SHIP
WHERE O.RESULT != 'sunk' OR O.RESULT IS NULL

--3
SELECT C.COUNTRY, COUNT(O.RESULT)
FROM CLASSES C LEFT JOIN SHIPS S ON C.CLASS = S.CLASS
LEFT JOIN OUTCOMES O ON O.SHIP = S.NAME
WHERE O.RESULT = 'sunk' OR S.NAME IS NULL OR O.RESULT IS NULL
GROUP BY C.COUNTRY

--4
SELECT O.BATTLE
FROM OUTCOMES O
GROUP BY O.BATTLE
HAVING COUNT(*) > (SELECT COUNT(*) FROM OUTCOMES WHERE BATTLE = 'Guadalcanal')

--5
SELECT O.BATTLE
FROM OUTCOMES O JOIN SHIPS S ON O.SHIP = S.NAME
JOIN CLASSES C ON C.CLASS = S.CLASS
GROUP BY O.BATTLE
HAVING COUNT(DISTINCT C.COUNTRY) > (SELECT COUNT(DISTINCT C.COUNTRY)
FROM OUTCOMES O JOIN SHIPS S ON O.SHIP = S.NAME
JOIN CLASSES C ON C.CLASS = S.CLASS
WHERE O.BATTLE = 'Surigao Strait')

--6
SELECT S.NAME, C.DISPLACEMENT, C.NUMGUNS
FROM CLASSES C JOIN SHIPS S ON C.CLASS = S.CLASS
WHERE C.DISPLACEMENT = (SELECT MIN(DISPLACEMENT) FROM CLASSES)
AND C.NUMGUNS = (SELECT MAX(NUMGUNS) FROM CLASSES WHERE DISPLACEMENT =
(SELECT MIN(DISPLACEMENT) FROM CLASSES))

--7
SELECT COUNT(*) AS NUM_SHIPS
FROM (OUTCOMES O1 JOIN BATTLES B1 ON O1.BATTLE = B1.NAME)
JOIN (OUTCOMES O2 JOIN BATTLES B2 ON O2.BATTLE = B2.NAME)
ON O1.SHIP = O2.SHIP
WHERE O1.RESULT = 'damaged' AND O2.RESULT = 'ok' AND B1.DATE < B2.DATE

--8
SELECT O1.SHIP
FROM (OUTCOMES O1 JOIN BATTLES B1 ON O1.BATTLE = B1.NAME)
JOIN (OUTCOMES O2 JOIN BATTLES B2 ON O2.BATTLE = B2.NAME)
ON O1.SHIP = O2.SHIP
WHERE O1.RESULT = 'damaged' AND O2.RESULT = 'ok' AND B1.DATE < B2.DATE
AND
(SELECT COUNT(DISTINCT SHIP) FROM OUTCOMES WHERE BATTLE = O1.BATTLE)
<
(SELECT COUNT(DISTINCT SHIP) FROM OUTCOMES WHERE BATTLE = O2.BATTLE)


use pc;
--1
SELECT MODEL, CODE, SCREEN
FROM LAPTOP
WHERE
(SCREEN = 11 AND 15 IN (SELECT SCREEN FROM LAPTOP L WHERE L.code = CODE))
OR
(SCREEN = 15 AND 11 IN (SELECT SCREEN FROM LAPTOP L WHERE L.code = CODE))

--2
SELECT DISTINCT PC.MODEL
FROM PC JOIN product P1 ON PC.model = P1.model
WHERE PRICE <
(SELECT MIN(PRICE) FROM LAPTOP L JOIN product P2 ON L.model = P2.model
WHERE P2.maker = P1.maker)

--3
SELECT PC.MODEL, AVG(PRICE) AS AVG_PRICE
FROM PC JOIN product P1 ON PC.model = P1.model
GROUP BY PC.MODEL, P1.MAKER
HAVING AVG(PRICE)
<
(SELECT MIN(PRICE) FROM LAPTOP L JOIN product P2 ON L.model = P2.model
WHERE P2.maker = P1.maker)

--4 kakvo e tova uslovie
SELECT PC.CODE, P.MAKER, 
(SELECT COUNT(*) FROM PC PC2 WHERE PC2.code != PC.CODE AND PC2.price >= PC.price)
AS NUM_PC_HIGHER_PRICE, PC.price
FROM PC JOIN product P ON PC.model = P.model
