use movies;
--1
INSERT INTO MOVIESTAR (NAME, GENDER, BIRTHDATE)
VALUES ('Nicole Kidman', 'F', '1967-06-20')

--2
DELETE FROM MOVIEEXEC
WHERE NETWORTH < 30000000

--3
DELETE FROM MOVIESTAR
WHERE ADDRESS IS NULL


use pc;
--4
INSERT INTO PRODUCT (model, maker, type)
VALUES (1100, 'C', 'PC')

INSERT INTO PC (CODE, MODEL, SPEED, RAM, HD, cd, price)
VALUES (12, '1100', 2400, 2048, 500, '52x', 299)

--5
DELETE FROM PC
WHERE MODEL = '1100' AND CODE != 12

--6
DELETE FROM LAPTOP
WHERE MODEL IN (SELECT MODEL FROM PRODUCT WHERE TYPE = 'Laptop' AND
MAKER NOT IN (SELECT DISTINCT MAKER FROM PRODUCT WHERE TYPE = 'Printer'))

--7
UPDATE product SET MAKER = 'A' WHERE MAKER = 'B'

--8
UPDATE PC SET HD=HD+20, PRICE=0.5*PRICE

--9
UPDATE LAPTOP SET SCREEN=SCREEN+1
WHERE MODEL IN (SELECT DISTINCT MODEL FROM PRODUCT WHERE TYPE = 'Laptop'
AND MAKER = 'B')


use ships;
--10
INSERT INTO SHIPS (CLASS, NAME, LAUNCHED)
VALUES ('Nelson', 'Nelson', 1927), ('Nelson', 'Rodney', 1927)

INSERT INTO CLASSES (CLASS, BORE, DISPLACEMENT, COUNTRY, TYPE)
VALUES ('Nelson', 16, 34000, 'Gt. Britain', 'bb')

--11
DELETE FROM SHIPS
WHERE NAME IN (SELECT SHIP FROM OUTCOMES WHERE RESULT = 'sunk')

--12
UPDATE CLASSES SET BORE=BORE*2.54, DISPLACEMENT=10*DISPLACEMENT/11
